server:
      port: 9000
spring:
  application:
    name: zuul-service
    #zuul:
    #  routes:
    #    blog:
    #        path: /ymq/**
    #        url: http://www.ymq.io/about

eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/


#Spring cloud zuul 默认情况下，Zuul会代理所有注册到Eureka Server的微服务，并且Zuul的路由规则如下：
#[http://ZUUL_HOST:ZUUL_PORT/]() 微服务在Eureka上的serviceId/**会被转发到serviceId对应的微服务。
zuul:
    prefix: /api
    routes:
        api:
#          path: /proController/getPort
          path: /**
          serviceId: server-provider