
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
        #远程git仓库地址
          uri: https://github.com/nihaoyuhuan2016/learngit.git
          search-paths: springcloud-config
#         username: nihaoyuhuan2016
#         password: eee
  #spring bus相关配置,使用rabbitMQ
  rabbitmq:
    host: 192.168.7.104
    port: 5672
    username: admin
    password: admin

server:
  port: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#Spring boot 2.0的改动较大，/bus/refresh全部整合到actuator里面了，变成了/actuator/bus-refresh,所以之前1.x的management.security.enabled全部失效，不适用于2.0
#  注意：config-server和config-client的配置都需要加上
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

#encrypt:
#  key: 123456789
